version: '3'

services:
  nest-boilerplate:
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-boilerplate
    container_name: nest-boilerplate
    restart: always
    ports: 
      - 5000:3000