http: 
  port: 3000
  
database:
  mongodb:
    host: localhost
    port: 27017
    userName: root
    password: toor
    database: test
  postgres:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: test